plot4 <- function() {
  png(file = "plot4.png")
  house <- read.csv("household_power_consumption.txt", sep = ";")
  housefeb <- subset(house, house$Date == "1/2/2007" | house$Date == "2/2/2007")
  housefeb$Time <- paste(housefeb$Date, housefeb$Time)
  housefeb$Time <- strptime(housefeb$Time, "%d/%m/%Y %H:%M:%S")
  housefeb$Global_active_power <- as.numeric(as.character(housefeb$Global_active_power))
  housefeb$Global_reactive_power <- as.numeric(as.character(housefeb$Global_reactive_power))
  housefeb$Sub_metering_1 <- as.numeric(as.character(housefeb$Sub_metering_1))
  housefeb$Sub_metering_2 <- as.numeric(as.character(housefeb$Sub_metering_2))
  housefeb$Sub_metering_3 <- as.numeric(as.character(housefeb$Sub_metering_3))
  housefeb$Voltage <- as.numeric(as.character(housefeb$Voltage))
  par(mfrow=c(2,2))
  plot(housefeb$Time, housefeb$Global_active_power, ylab = "Global Active Power (kilowatts)", xlab = "" , type = "l")
  plot(housefeb$Time, housefeb$Voltage, ylab = "Voltage", xlab = "datetime" , type = "l")
  plot(housefeb$Time, housefeb$Sub_metering_1, ylab = "Energy sub metering", xlab = "" , type = "l")
  points(housefeb$Time, housefeb$Sub_metering_2, col = "red", type = "l")
  points(housefeb$Time, housefeb$Sub_metering_3, col = "blue", type = "l")
  legend(x = "topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), cex = 0.4, lwd=2)
  plot(housefeb$Time, housefeb$Global_reactive_power, ylab = "Global_reactive_power", xlab = "datetime" , type = "l")
  dev.off()
}